# Test ortamı için log seviyelerini ayarla
logging:
  level:
    # Kendi paketlerimiz için DEBUG seviyesi
    com.avmerkez.mallservice: DEBUG
    # Spring Web ve Security katmanları için DEBUG (Sorun anında TRACE de denenebilir)
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    # Hibernate SQL loglaması (Opsiyonel, çok fazla log üretebilir)
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type.descriptor.sql: TRACE # Parametreleri görmek için 