spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/v1/search/**