# Configurations loaded AFTER bootstrap.yml and config server properties

# Eureka Client Configuration (Can also be fetched from config server via application.yml in Git)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Gateway and Actuator settings are now expected to come from the config server
# (api-gateway.yml and application.yml in the Git repo)

# JWT Fallback Secret (Should ideally come entirely from Config Server)
avmerkez:
  app:
    # jwtSecret: fallbackSecretKeyLongerThan256BitsForHS256 # Fetched from Config Server
    # jwtCookieName: avm_jwt # Fetched from Config Server
    # jwtIssuer: avmerkez-auth-service # Fetched from Config Server as avmerkez-user-service
    # jwtAudience: avmerkez-app # Fetched from Config Server

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, prometheus, metrics # Gateway specific endpoints
  # Micrometer Tracing Configuration
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: B3 