# Configurations loaded AFTER bootstrap.yml and config server properties

# Eureka Client Configuration (Can also be fetched from config server via application.yml in Git)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Gateway and Actuator settings are now expected to come from the config server
# (api-gateway.yml and application.yml in the Git repo)

# JWT Fallback Secret (Should ideally come entirely from Config Server)
avmerkez:
  app:
    jwtSecret: fallbackSecretKeyLongerThan256BitsForHS256 # Fallback if not provided by config server

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, prometheus, metrics # Gateway specific endpoints
  # Micrometer Tracing Configuration
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: B3 