# Bu dosya artık çoğunlukla boş olabilir veya sadece lokal geliştirme profilleri
# gibi Config Server'dan *gelmeyecek* ayarları içerebilir.

spring:
  # Aktif profili ortam değişkeninden al (veya lokal geliştirme için varsayılan ata)
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Config Server import direktifi bootstrap.yml'de olduğu için burada tekrar gerekmez,
  # ama bazı Spring versiyonları/yapılandırmaları için burada da olması gerekebilir.
  # Emin olmak için ikisinden birinde olması yeterlidir.
  # config:
  #   import: optional:configserver:${spring.cloud.config.uri:http://localhost:8888}
