# Configurations loaded AFTER bootstrap.yml and config server properties
# Can contain local overrides or properties not suitable for config server

avmerkez:
  app:
    jwtSecret: ${JWT_SECRET:c2VjcmV0IGtleSBtdXN0IGJlIGxvbmcgdGhhbiAyNTYgYml0cw==} # Use environment variable or Vault
    jwtExpirationMs: ${JWT_EXPIRATION_MS:3600000}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: B3

# Default port (can be overridden by environment or config server)
server:
  port: 8083

spring:
  application:
    name: user-service
  # Yeni Spring Cloud Config yaklaşımı - configserver: ile başlayan import'u opsiyonel yap
  config:
    import: optional:configserver:${spring.cloud.config.uri:http://localhost:8888}
  
  # Config Client Configuration
  cloud:
    config:
      fail-fast: false # Config server bulunamazsa fail olma
      enabled: true
      uri: http://localhost:8888
      profile: default
      label: main
      request-connect-timeout: 5000
      request-read-timeout: 10000 