# Bu dosya artık çoğunlukla boş olabilir.

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
   import: configserver:${spring.cloud.config.uri:http://localhost:8888}
  redis:
    host: localhost
    port: 6379