server:
  port: 8086 # Changed port

spring:
  application:
    name: campaign-event-service # Changed
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/campaign_event_service_db} # Changed DB name
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration # Ensure this directory exists
    schemas: public

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: true

# Config server should manage JWT secrets etc. in production
avmerkez:
  app:
    serviceName: campaign-event-service

management:
  endpoints:
    web:
      exposure:
        include: "*" # Restrict in production profile
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0 # Set lower for production
    propagation:
      type: B3

logging:
  level:
    root: INFO
    com.avmerkez.campaigneventservice: DEBUG # Changed package
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method 