# Server port for the Config Server
server:
  port: 8888 # Default Config Server port

# Spring Application Name
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # !!! KENDİ DEPO ADRESİNİZLE DEĞİŞTİRİN !!!
          uri: https://github.com/kcguran/avmerkez-config-repo.git # <-- BURAYI GÜNCELLEYİN
          # Optional: If the repository is private
          # username: your-git-username
          # password: your-git-password or token
          # Optional: Search paths within the repository
          # search-paths: 'config/{application}, config/shared'
          default-label: main # Default branch to use
          # Optional: Clone on start to fetch config immediately
          # clone-on-start: true
        # Optional: Enable native profile for local file system backend (instead of Git)
        # native:
        #   search-locations: classpath:/config, file:./config

# Eureka Client Configuration (To register with Discovery Server)
eureka:
  client:
    service-url:
      # Point to the Discovery Server
      defaultZone: http://localhost:8761/eureka/
    # Optional: Fetch registry periodically
    # fetch-registry: true
    # Optional: Register itself with Eureka
    # register-with-eureka: true
  instance:
    # Prefer IP address for registration (useful in containerized environments)
    prefer-ip-address: true
    # Optional: Customize instance ID
    # instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Optional: Actuator endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, env, configprops # Expose useful endpoints 