server:
  port: 8085

spring:
  application:
    name: review-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/review_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: true

# Aşağıdaki konfigürasyonlar dev ortamı için varsayılan değerlerdir,
# prod ortamında config server üzerinden yönetilecektir
avmerkez:
  app:
    # JWT ile ilgili konfigürasyonlar yoruma alındı, config server üzerinden gelecek
    # jwtSecret: ${JWT_SECRET:changeitChangeitChangeitChangeitChangeitChangeitChangeitChangeit}
    # jwtExpirationMs: ${JWT_EXPIRATION:86400000} # 24 saat
    serviceName: review-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  # Micrometer Tracing Configuration
  tracing:
    sampling:
      probability: 1.0 # %100 trace for dev/test. Set to a lower value for production (e.g. 0.1 for 10%)
    propagation:
      type: B3 # Standard B3 propagation for Zipkin compatibility

logging:
  level:
    root: INFO
    com.avmerkez.reviewservice: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG # SQL sorguları için (geliştirme ortamında)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Sorgu parametreleri için (geliştirme ortamında)

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method 